steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/gateway/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/botbond/gateway:${_IMAGE_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/botbond/gateway:${_IMAGE_TAG}
substitutions:
  _REGION: us-central1
  _IMAGE_TAG: manual
